include(
    ":app",
    ":core",
    ":oauth",
    ":oauthdependencies",
    ":oauthstorage",
    ":oauthadaptergenerator",
    ":oauthmoshi",
    ":oauthmoshikoin",
    ":oauthgson",
    ":oauthparsing",
    ":oauthsecurestorage",
    ":oauthsecurestoragecompat"
)