name: Verify Pull request is publishable

on:
  pull_request:
    branches:
      - develop

env:
  GITHUB_USERNAME: "halcyonmobile"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run Android Unit Tests
        run: ./gradlew testReleaseUnit
      - name: Run Core Unit Tests
        run: ./gradlew core:test
